use std::ops::Range;

use uuid::Uuid;

/// User-visible state changes. Effects such as saving remain at the UI boundary.
#[derive(Clone, Debug, Eq, PartialEq)]
pub enum Command {
    ToggleHelp,
    CloseHelp,
    ToggleMode,
    ToggleCommentFocus,
    FocusDocument,
    BeginSearch,
    AppendSearchCharacter(char),
    DeleteSearchCharacter,
    NextSearchMatch,
    PreviousSearchMatch,
    CloseSearch,
    Insert(char),
    DeleteBackward,
    Undo,
    Redo,
    MoveRawLeft { select: bool },
    MoveRawRight { select: bool },
    MoveRawUp { select: bool },
    MoveRawDown { select: bool },
    MoveNextBlock,
    MovePreviousBlock,
    SetRawSelection(Range<usize>),
    AddComment(String),
    BeginComment,
    BeginEditSelectedComment,
    AppendCommentCharacter(char),
    DeleteCommentCharacter,
    MoveCommentCursorLeft,
    MoveCommentCursorRight,
    MoveCommentCursorWordLeft,
    MoveCommentCursorWordRight,
    MoveCommentCursorStart,
    MoveCommentCursorEnd,
    SubmitComment,
    CancelComment,
    SelectNextComment,
    SelectPreviousComment,
    JumpToSelectedComment,
    ToggleSelectedCommentResolution,
    DeleteSelectedComment,
    RepairSelectedOrphan,
    ResolveComment(Uuid),
    DeleteComment(Uuid),
    RepairComment(Uuid),
    SaveCompleted,
}
